(cl:defpackage pedsim_msgs-msg
  (:use )
  (:export
   "<AGENTSTATE>"
   "AGENTSTATE"
   "<TRACKEDGROUP>"
   "TRACKEDGROUP"
   "<TRACKEDPERSON>"
   "TRACKEDPERSON"
   "<TRACKEDPERSONS>"
   "TRACKEDPERSONS"
   "<SOCIALACTIVITY>"
   "SOCIALACTIVITY"
   "<TRACKEDGROUPS>"
   "TRACKEDGROUPS"
   "<ALLAGENTSSTATE>"
   "ALLAGENTSSTATE"
   "<SOCIALRELATION>"
   "SOCIALRELATION"
   "<SOCIALRELATIONS>"
   "SOCIALRELATIONS"
   "<SOCIALACTIVITIES>"
   "SOCIALACTIVITIES"
  ))

